"""empty message

Revision ID: 645bb39ae7e8
Revises: ea3a959d1711
Create Date: 2023-04-05 02:29:29.997178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645bb39ae7e8'
down_revision = 'ea3a959d1711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('idx-profiles_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index('idx-profiles_user_id')

    # ### end Alembic commands ###
