"""empty message

Revision ID: 91a5578ce728
Revises: 96d2a1d6411a
Create Date: 2023-04-12 15:46:54.677406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a5578ce728'
down_revision = '96d2a1d6411a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_profiles_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_profiles_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
