"""add profiles table

Revision ID: ea3a959d1711
Revises: 42daf15b234d
Create Date: 2023-04-05 02:21:39.512255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3a959d1711'
down_revision = '42daf15b234d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_profiles_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_user_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_password', ['password'], unique=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('profiles')
    # ### end Alembic commands ###
